### ISSUE TITLE
Support dataframe protocol

### ISSUE THREAD

**Issue by jonmmease** [hex-inc/vegafusion#243]
@ChristopherDavisUCI recently added support to Altair for working with non-pandas DataFrames that support the [`.__dataframe__()` protocol](https://data-apis.org/dataframe-protocol/latest/index.html). This adds Altair support for Polars and other DataFrame libraries that implement the protocol.

We should take advantage of this in VegaFusion to support Polars and others without converting to pandas (working with PyArrow directly).

**Comment by ChristopherDavisUCI** [comment]
Thank you!  I just need to say @mattijn deserves all the credit (and any questions related to the `.__dataframe__()` protocol ;)
