### ISSUE TITLE
Mimerenderer always replaces first chart in VS Code notebook

### ISSUE THREAD

**Issue by binste** [hex-inc/vegafusion#245]
When enabling the mimerenderer, the first chart in a notebook in VS Code works fine. However, any subsequent charts always modify the output of the first cell with a chart. The screencast below shows how it looks when executing the exact same chart specifications again but setting `color="green"` the second time around.

https://user-images.githubusercontent.com/23366411/222985137-5ee14003-c33f-45aa-a796-67dd2778de07.mov

Using the developer tools, I saw that the id for the chart `div` is `altair-viz-{}` for both charts so presumably a unique hash which should be added instead of `{}` is not properly rendered in the html output which leads to the javascript code always referencing the first chart div?

<img width="476" alt="image" src="https://user-images.githubusercontent.com/23366411/222985351-a44b7cf2-c486-4480-b215-09523122ae62.png">

* VegaFusion 1.0.3
* Python 3.10.8
* VS Code 1.75.1 (extensions: Jupyter v2023.1.2010391206, Python v2023.4.0)
* MacOSX Ventura 13.1 M2 Chip

**Comment by jonmmease** [comment]
Thanks for the report!

> Using the developer tools, I saw that the id for the chart div is altair-viz-{} for both charts so presumably a unique hash which should be added instead of {} is not properly rendered in the html output which leads to the javascript code always referencing the first chart div?

Great detective work. Yeah, this div should have a unique ID. I'll take a look shortly to see where that's getting missed.

**Comment by jonmmease** [comment]
Fixed in 1.0.4 as part of https://github.com/hex-inc/vegafusion/pull/246

**Comment by binste** [comment]
That was fast, thank you! Can confirm that it works as expected with 1.0.4
