### ISSUE TITLE
Saved altair chart is empty

### ISSUE THREAD

**Issue by debbes80** [hex-inc/vegafusion#284]
Saving an altair chart (`chart.save('chart.png)`) leads to an empty plot (axes but no data points). This happens with saving to html, png and svg and with using the mimetypes html, png, svg.
The rendering in Jupyterlab is ok and saving (to png or svg) via the vega actions menu also works fine.

Without `vf.enable()`:
![chart](https://user-images.githubusercontent.com/54935651/227795328-42276a29-325f-457c-b024-059575dff3c9.png)
With `vf.enable()`:
![chart_vf](https://user-images.githubusercontent.com/54935651/227795335-efdf8792-cf9c-42b6-885c-8b1a1b0bf552.png)

versions:
> altair                   5.0.0rc1
> vegafusion               1.1.1
> vegafusion-python-embed  1.1.1
> vl-convert-python        0.7.0

**Comment by jonmmease** [comment]
Thanks for the report @debbes80! I'll take a look

**Comment by jonmmease** [comment]
I can reproduce the issue with Altair 5.0.0rc1, but it's fixed on Altair `master`. I think this PR took care of the issue: https://github.com/altair-viz/altair/pull/2954

**Comment by debbes80** [comment]
Can confirm, thanks!
