### ISSUE TITLE
Grouped density estimates are not computed/rendered correctly

### ISSUE THREAD

**Issue by joelostblom** [hex-inc/vegafusion#381]
This chart works fine in altair:

```py
import altair as alt
from vega_datasets import data

alt.Chart(data.movies.url).transform_filter(
    {"field": "Major_Genre", "oneOf": ["Action", "Drama"]}
).transform_density(
    'IMDB_Rating',
    groupby=['Major_Genre'],
    as_=['IMDB_Rating', 'density'],
).mark_area().encode(
    x="IMDB_Rating:Q",
    y='density:Q',
    color='Major_Genre:N'
)
```

![image](https://github.com/hex-inc/vegafusion/assets/4560057/98c36490-7e43-43fa-a9fe-7028a5882984)

But after enabling the vegafusion data transformer, the grouping is messed up:

![image](https://github.com/hex-inc/vegafusion/assets/4560057/a1cf8e69-fd6c-4dca-8571-fd16cc9679bd)

The appearance of the issue is similar to what was reported in https://github.com/vega/vega-lite/issues/8049, but setting `steps` explicitly does not seem to fix this bug.

**Comment by jonmmease** [comment]
woah, that's weird. Thanks for the report. VegaFusion doesn't perform the density transform itself yet, so I'm guessing it's messing up the order somewhere.

**Comment by jonmmease** [comment]
Huh, I'm actually seeing this behavior without VegaFusion as well. Here's the Vega-Lite spec that Altair 5.1.1 is producing:

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYcAvpO50AhoTl4QpAE4AbFCDGEADpWQB6Q2DpQAdACtKdTOrhpV5qJkKGougLaG0mBHIBaeUVKV0oAATQARnMAJgBOczZDYLlDTwgMTEorSmgQGRBPOVUAa2VCAE9dTC0SzCVCzChIOhIkVB51CFVleDs6LQBZOUsegH0AcWbVWu4qmq0oCE8SOU1CgA8+rHVB5BAASSGAEQAhcYAlBXaQeerag4BHUjkiOEViXwLuSp2BrS2KCUD5-e6LZ6vd6fBy1aTzVRvSgwHqeFAAbVA8HUhEwvU6-T2w1GE2mUFmdxA0EwAHkYBiQABBMDEfLcE6I4ogAC68NAQJBVS0x3OVxuUCQ3AQqgougARn9kOiQCMxqopjNatzuHJKAyRRdrnxJSABaCeZJtSAACSUMCMTBcg46fRGHx+OTmBAfRikOXmOAQQx2h3Fd3+AL2XE+ACs5iiABZ47l8pIgA)

![visualization](https://github.com/hex-inc/vegafusion/assets/15064365/46127670-545d-46a0-a8c2-0741a46790c2)

Could you share the Vega-Lite produced in the working case for you?

**Comment by jonmmease** [comment]
Reported, with proposed fix, in https://github.com/vega/vega-lite/issues/9078. I think Vega-Lite needs to specify `"resolve": "shared"` in the `kde` Vega transform that Vega-Lite produces. It doesn't look like Vega-Lite accepts this parameter in the density transform, so I don't think there's anything we can do on the Altair (or VegaFusion) side unfortunately.

**Comment by joelostblom** [comment]
I was so perplexed initially by seeing that it didn't work in VL, but now I know what happened. The regression seem to have been introduced after VL 5.8, so it works fine in altair 5.0.1. Our docker container has 5.0.1 installed so I launched JupyterLab and ran it with this version first. Then realized I should use Altair 5.1.1, so I reinstalled it in the notebook and restarted the kernel but not the notebook itself, so all the specs were still evaluated using altair 5.0.1 and VL 5.8 when using the default renderer; it seems like the vegafusion renderer will correctly detect the updated altair and use the later version but the notebook will not hot reload the VL version. This leads to really confusing behavior as you can see in the video I posted here https://github.com/vega/editor/issues/336#issuecomment-1705536164

**Comment by mattijn** [comment]
But new Python functionality does work? Like `JupyterClass`? 

Really confusing..

I thought I find out in the previous time this issue was discussed that the newest version of Vega-Lite is loaded and then also will be used for defined altair visualizations in other open notebooks (within the same JupyterLab session). 

But the behavior here seems different as the first cached JavaScript (?) package of Vega-lite is not renewed when a newer Vega-lite JS is referenced.

**Comment by joelostblom** [comment]
> I thought I find out in the previous time this issue was discussed that the newest version of Vega-Lite is loaded and then also will be used for defined altair visualizations in other open notebooks (within the same JupyterLab session).

Hmm, I don't think that is the case. I ran the notebook once with the old version, pip installed the new version in the notebook and restarted the kernel. See this video (I'm at a super slow internet right now which is why things take so long):


https://github.com/hex-inc/vegafusion/assets/4560057/5d97b240-66e9-434b-bb1d-931d038a3f2d
