### ISSUE TITLE
Support Vega-Embed Themes

### ISSUE THREAD

**Issue by MarcSkovMadsen** [hex-inc/vegafusion#64]
With Altair I can normally set a dark theme using `alt.themes.enable("dark")`. It seems not to be working when using vegafusion-jupyter.

## Works without VegaFusion

![image](https://user-images.githubusercontent.com/42288570/151690580-9687901e-81c2-4c83-93fe-32dc0ced6101.png)

## Does not work with VegaFusion

![image](https://user-images.githubusercontent.com/42288570/151690599-0c922878-23f9-44be-9abb-1db0183f3dc7.png)

## Code

```python
import vegafusion_jupyter as vf
vf.enable()

import altair as alt
from vega_datasets import data

alt.themes.enable("dark")

source = data.seattle_weather()
brush = alt.selection(type='interval', encodings=['x'])

bars = alt.Chart().mark_bar().encode(
    x='month(date):O',
    y='mean(precipitation):Q',
    opacity=alt.condition(brush, alt.OpacityValue(1), alt.OpacityValue(0.7)),
).add_selection(
    brush
)

line = alt.Chart().mark_rule(color='firebrick').encode(
    y='mean(precipitation):Q',
    size=alt.SizeValue(3)
).transform_filter(
    brush
)

chart = alt.layer(bars, line, data=source)
chart
```

**Comment by jonmmease** [comment]
Thanks for the report, I think the theme logic is part of vega-embed which VegaFusion isn't using. But we should port over that logic.

**Comment by jonmmease** [comment]
Done in 1.0
